version: '3'
services:
  client:
    image: nginx
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  login-spa:
    image: nginx
    volumes:
      - ./login-spa:/usr/share/nginx/html:ro
    ports:
      - "8082:80"

  api:
    build: ./api
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Authority=http://id4

  id4:
    build: ./id4
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Issuer=http://id4
